services:
  app:
    build:
      context: .
      target: ${TARGET_STAGE:-dev}
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/src
  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
